### ISSUE TITLE
Julia QuadGK: "MethodError: no method matching DomainError()"

### ISSUE THREAD

**Issue by aaabdulhaq** [JuliaMath/QuadGK.jl#29]
Following is my code to solve two-dimensional integral in Julia.

```julia
using Statistics,Distributions,Distributed,StatsFuns,Roots,QuadGK
p=3;n0=3;n1=1;n2=29;d=0.25;
inARL=200;n=n1+n2;w1=chisqinvcdf(p,1-(n0-n1)/n2);inpa1=chisqcdf(p,w1);

function inpa(h2)
function fvv(v)
return(nchisqcdf(p,(n1/n2)v,(nh2)/n2)*chisqpdf(p,v));end;
return(1/(1-inpa1-quadgk(fvv,w1,Inf,rtol=1e-10)[1])-inARL);end;

h=fzero(inpa,0.25,50);
outpa1=nchisqcdf(p,n1*d^2,w1);

function fz1(z)
function fv1(v)
lam=(n1/n2)((z+sqrt(n1)d)^2+v)+(2nsqrt(n1)dz)/(n2)+((nd)^2)/(n2);
return(nchisqcdf(p,lam,(nh)/n2)*chisqpdf(p-1,v));end;
return(normpdf(z)*quadgk(fv1,0,Inf,rtol=1e-10)[1]);end;
int1=quadgk(fz1,-Inf,-sqrt(w1)-sqrt(n1)*d,rtol=1e-10)[1];#here is the problem
```

**Comment by ararslan** [comment]
Fixed by #28. I just tagged a new release, so the change should be visible to you once https://github.com/JuliaLang/METADATA.jl/pull/17656 is merged and you run `Pkg.update()`.

**Comment by aaabdulhaq** [comment]
Dear Arslan!

Thank you for your help. I wanna know how long it will take the error to be removed.

Looking forward to your response.

**Comment by aaabdulhaq** [comment]
I've checked it again, the problem is still there!

**Comment by aaabdulhaq** [comment]
I've checked it again, the problem is still there! It now says:
ERROR: LoadError: DomainError with 0.5:
integrand produced NaN in the interval (0.0, 1.0)

**Comment by ararslan** [comment]
Should be good now once you run `Pkg.update()`.
